#!/usr/bin/env bash
#
# Build Libron locally inside the fntbld container via Podman.
#
# This mirrors the CI build: it mounts the repository into the prebuilt
# fntbld image (which bundles FontForge, ttfautohint, fonttools, brotli,
# and skia-pathops) and runs build.py. Generated fonts appear in ./out
# on the host.
#
# Usage:
#   ./local-build.sh                           # full build incl. Kobo + Nerd Fonts + mono variants
#   ./local-build.sh --without-kobofix         # skip generating Kobo (KF) variants
#   ./local-build.sh --without-nerdfonts       # skip generating Nerd Fonts variants
#   ./local-build.sh --without-nerdfonts-mono  # skip the Nerd Fonts mono variant
#   ./local-build.sh --customize               # any build.py flags are passed through
#
# Kobo (KF), Nerd Fonts and Nerd Fonts mono variants are generated by default
# here. build.py itself defaults to off and takes --with-kobofix /
# --with-nerdfonts / --with-nerdfonts-mono; this wrapper flips those defaults
# for local builds and accepts --without-* to opt out.
#
set -euo pipefail

IMAGE="${FNTBLD_IMAGE:-ghcr.io/nicoverbruggen/fntbld-oci:latest}"

# Resolve the repository root (directory of this script) so the build works
# no matter where it is invoked from.
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if ! command -v podman >/dev/null 2>&1; then
  echo "ERROR: podman not found. Install Podman from https://podman.io" >&2
  exit 1
fi

echo "Building Libron with ${IMAGE}"
echo

# Kobo fix, Nerd Fonts and the mono variant are on by default; let the user
# opt out with --without-*. build.py only understands --with-*, so translate
# accordingly and pass every other argument through untouched.
with_kobofix=1
with_nerdfonts=1
with_nerdfonts_mono=1
args=()
for arg in "$@"; do
  case "${arg}" in
    --without-kobofix)        with_kobofix=0 ;;
    --with-kobofix)           with_kobofix=1 ;;
    --without-nerdfonts-mono) with_nerdfonts_mono=0 ;;
    --with-nerdfonts-mono)    with_nerdfonts_mono=1 ;;
    --without-nerdfonts)      with_nerdfonts=0 ;;
    --with-nerdfonts)         with_nerdfonts=1 ;;
    *)                        args+=("${arg}") ;;
  esac
done

if [ "${with_kobofix}" -eq 1 ]; then
  args+=("--with-kobofix")
fi

if [ "${with_nerdfonts}" -eq 1 ]; then
  args+=("--with-nerdfonts")
fi

if [ "${with_nerdfonts_mono}" -eq 1 ]; then
  args+=("--with-nerdfonts-mono")
fi

podman run --rm \
  -v "${REPO_DIR}":/work:z \
  -w /work \
  "${IMAGE}" \
  python3 build.py ${args[@]+"${args[@]}"}